---
title: "Assignment 2"
author: "Mike Segura"
date: "August 22, 2018"
output: html_document
---


### Load several functions in the event they're not loaded
```{r echo = FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(reshape2)
#library(lubridate)
```

### Question #1: Import Activity file and remove NA from steps column
```{r echo = TRUE}
ActivityDataImport <- read.csv("activity.csv")
## Remove NA in data
Final_Data <- ActivityDataImport[ with (ActivityDataImport, { !(is.na(steps)) } ), ]
```


### Question #2: What is mean total number of steps taken per day?
```{r echo = TRUE}
## Part A: Calculate the total number of steps taken per day

summary(Final_Data$steps)

## Group for by date steps aggregation
ByDate <- group_by (Final_Data, date)
StepsByDate <- summarise(ByDate, total = sum(steps))
StepsByDate

## Part B: Make a histogram of the total number of steps taken each day
hist(StepsByDate$total, col = "green", main="Histogram of Total Steps by Day",
                      xlab = "Total Number of Steps in a Day")

## Part C: Calculate and report the mean and median of the total number of steps taken per day
summary(StepsByDate)

```
### Question #3: What is the average daily activity pattern?
```{r echo=TRUE}
## Part A: Make a time series plot (i.e.type="l") of the 5-minute interval (x-axis) and the 
## average number of steps taken, averaged across all days (y-axis).
DailyAVG <- aggregate(x=list(steps=Final_Data$steps), by=list(interval=Final_Data$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=DailyAVG, aes(x=interval, y=steps), type = "1") +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken")

## Part B: Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

MaxInterval <- which.max(DailyAVG$steps)
DailyAVG[MaxInterval, ]

```

### Question #3: Imputing missing values
```{r echo = TRUE}

## Part A: Calculate and report the total number of missing values in the dataset
## i.e. the total number of rows with NAs.
NA_ROWS <- sum(is.na(ActivityDataImport))
NA_ROWS

## Part B: Devise a strategy for filling in all of the missing values in the dataset. 
## Part C:Create a new dataset that is equal to the original dataset but with the missing data filled in.
ActivityIMPUTE <- ActivityDataImport
ActivityIMPUTE$steps[is.na(ActivityIMPUTE$steps)] <- mean(ActivityDataImport$steps, na.rm = TRUE)

## checking on NA counts
colSums(is.na(ActivityIMPUTE))

## Part D: Make a histogram of the total number of steps taken each day and Calculate and 
## report the mean and median total number of steps taken per day.
ImputeSteps <- tapply(ActivityIMPUTE$steps, ActivityIMPUTE$date, sum)

ImputSteps2 <- melt(ImputeSteps)
names(ImputSteps2) <- c("Date", "SumofSteps")

hist(ImputSteps2$SumofSteps, main = "Histogram of Total Number of Steps per Day on  Impute Value", 
    xlab = "Total Number of Steps per Day", ylab = "Frequency", col = "blue")

##  Do these values differ from the estimates from the first part of the assignment? 

## Original Data Set
summary(Final_Data$steps)
## Imputed Data Set
summary(ActivityIMPUTE$steps)
## Imputed Data Set -- comparison if this new data set to the original. 3rd quartile looks larger but 
## others look inline with original data set values.

## What is the impact of imputing missing data on the estimates of the total daily number of steps?
### ANSWER: it increased the number of instances where total number of steps existed between 10,000 and 15,000 total
### number of steps in a day.

```

### Question #4: Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}

WDay_Wend <- function(date) {
    day <- weekdays(date)
    if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")) 
        return("weekday") else if (day %in% c("Saturday", "Sunday")) 
        return("weekend") else stop("invalid date")
}

ActivityIMPUTE$date <- as.Date(ActivityIMPUTE$date)
ActivityIMPUTE$day <- sapply(ActivityIMPUTE$date, FUN = WDay_Wend)

averages <- aggregate(steps ~ interval + day, data = ActivityIMPUTE, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) + 
    xlab("5-minute interval") + ylab("Number of steps")

## ANSWER: It looks like overall the weekend has more intervals of over 100 steps, however, 
## this was using Imputed data and that may or may not reflect actual historical patterns.
## Looks like the average steps by interval is higest within the weekday 800 interval
## which is within the 8:00 AM hour of the day. Could be the steps of people commuting to work.

```

